# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    parameters:
      game-version:
        type: string
    docker:
      - image: variantxyz/rgbds-20200621:f996186fae53fa87b1f7a8b3373d91211601d21d
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4f:8a:7b:39:92:9f:c1:33:12:ea:98:fe:a2:6d:58:0f"
      - checkout:
          path: ~/medarot_1
      - run:
          name: "Get base"
          working_directory: ~
          command: git clone --quiet $BASEROM_REPO ~/medarot_baserom && cp ~/medarot_baserom/medarot_<< parameters.game-version >>.gb ~/medarot_1/baserom_<< parameters.game-version >>.gb
      - run:
          name: "Build ROM"
          working_directory: ~/medarot_1
          command: make << parameters.game-version >> -j

workflows:
  workflow:
    jobs:
      - build:
          name: "Parts Collection"
          game-version: "parts_collection"