import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), 'common'))
from common import utils, tilesets

script_name = sys.argv[0]
output_file = sys.argv[1]
res_file = sys.argv[2]

table = utils.read_table(res_file)
with open(output_file, "w") as tf:
    tf.write(f"; auto-generated by {script_name}\n")
    tilemap_files = []
    # Pointer table
    for i in table:
        if not table[i]:
            tf.write("dw TILEMAPS_END ; NULL\n")
            continue
        tmap_name = os.path.splitext(os.path.basename(table[i]))[0]
        tf.write(f"dw {tmap_name} ; Tilemap 0x{i:02X}\n")
        if tmap_name not in tilemap_files:
            tilemap_files.append(tmap_name)
    tf.write("\n")
    for file in tilemap_files:
        tf.write(f'{file}:\n  INCBIN "build/tilemaps/{file}.tmap"\n')
    tf.write("TILEMAPS_END::")